name: authentik
services:
  authentik-proxy:
    image: ghcr.io/goauthentik/proxy:2025.12.1@sha256:05d08f10759ece45acf498bd09ce99f3bb8a36cd69aaac10d601cbc35c4f47aa
    container_name: authentik-proxy
    secrets:
      - authentik_token
    environment:
      AUTHENTIK_HOST: ${AUTHENTIK_HOST}
      AUTHENTIK_TOKEN: file:///run/secrets/authentik_token
    networks:
      - authentik-proxy-web
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.port: 9000
      traefik.http.routers.authentik.rule: PathPrefix(`/outpost.goauthentik.io/`)
      traefik.http.routers.authentik.priority: 1
      traefik.http.middlewares.authentik.forwardauth.address: http://authentik-proxy:9000/outpost.goauthentik.io/auth/traefik
      traefik.http.middlewares.authentik.forwardauth.trustForwardHeader: true
      traefik.http.middlewares.authentik.forwardauth.authResponseHeaders: X-authentik-username,X-authentik-groups,X-authentik-entitlements,X-authentik-email,X-authentik-name,X-authentik-uid,X-authentik-jwt,X-authentik-meta-jwks,X-authentik-meta-outpost,X-authentik-meta-provider,X-authentik-meta-app,X-authentik-meta-version
    user: ${PUID}:${PGID}
networks:
  authentik-proxy-web:
    name: authentik-proxy-web
secrets:
  authentik_token:
    file: ../.secrets/authentik_token
