name: karakeep
services:
  karakeep-chrome:
    image: zenika/alpine-chrome:124@sha256:dbbe4612e677d952996ce1281ada255f58c5b6f8115f02e0dc075f2742a3de2b
    container_name: karakeep-chrome
    networks:
      - karakeep
    command:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --hide-scrollbars
    restart: unless-stopped
    labels:
      glance.parent: karakeep
      glance.name: Chrome
      glance.category: cloud
  karakeep-meilisearch:
    image: getmeili/meilisearch:v1.24.0@sha256:d991eb07331e9d1f9cec7bc0f9523fd5d51aee3b223d997e0e66206361952056
    container_name: karakeep-meilisearch
    volumes:
      - ${DATA_DIR}/meilisearch/karakeep:/meili_data
    environment:
      - MEILI_NO_ANALYTICS=true
    env_file: ../.secrets/karakeep_keys
    networks:
      - karakeep
    restart: unless-stopped
    labels:
      glance.parent: karakeep
      glance.name: Search
      glance.category: cloud
  karakeep-web:
    image: ghcr.io/karakeep-app/karakeep:0.28.0@sha256:cd2348520ba25bbee64199468cd41758ab325eecd6a3a5c40cd6443a1607f9e9
    container_name: karakeep-web
    volumes:
      - ${DATA_DIR}/karakeep:/data
    environment:
      - MEILI_ADDR=http://karakeep-meilisearch:7700
      - BROWSER_WEB_URL=http://karakeep-chrome:9222
      - NEXTAUTH_URL=https://karakeep.${HOST}
      - DATA_DIR=/data
    env_file: ../.secrets/karakeep_keys
    networks:
      - karakeep
      - karakeep-web
    restart: unless-stopped
    labels:
      readme.description: The Bookmark Everything App
      readme.links.web: https://karakeep.app/
      traefik.docker.network: karakeep-web
      traefik.enable: true
      traefik.http.routers.karakeep.entrypoints: https
      traefik.http.routers.karakeep.rule: Host(`karakeep.${HOST}`)
      glance.id: karakeep
      glance.name: Karakeep
      glance.icon: di:karakeep
      glance.url: https://karakeep.${HOST}
      glance.description: Bookmark Manager
      glance.category: cloud
networks:
  karakeep:
    name: karakeep
  karakeep-web:
    name: karakeep-web
