name: karakeep
services:
  karakeep-chrome:
    image: zenika/alpine-chrome:124@sha256:52fd6bf7736013acad7cf8679eaefdfc279dbea1038e6b040e2f1c361ed01e3f
    container_name: karakeep-chrome
    networks:
      - karakeep
    command:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --hide-scrollbars
    restart: unless-stopped
    labels:
      glance.parent: karakeep
      glance.name: Chrome
      glance.category: cloud
  karakeep-meilisearch:
    image: getmeili/meilisearch:v1.26.0@sha256:773759814f59214a0971dc8810ae1d85002e92166d99760cd546d5ee8ac37c14
    container_name: karakeep-meilisearch
    volumes:
      - ${DATA_DIR}/meilisearch/karakeep:/meili_data
    environment:
      - MEILI_NO_ANALYTICS=true
    env_file: ../.secrets/karakeep_keys
    networks:
      - karakeep
    restart: unless-stopped
    labels:
      glance.parent: karakeep
      glance.name: Search
      glance.category: cloud
  karakeep-web:
    image: ghcr.io/karakeep-app/karakeep:0.30.0@sha256:2724d4a9a6d13a7fa3babf53b9245767aae56c34f06042a8463ee983c6b41caf
    container_name: karakeep-web
    volumes:
      - ${DATA_DIR}/karakeep:/data
    environment:
      - MEILI_ADDR=http://karakeep-meilisearch:7700
      - BROWSER_WEB_URL=http://karakeep-chrome:9222
      - NEXTAUTH_URL=https://karakeep.${HOST}
      - DATA_DIR=/data
    env_file: ../.secrets/karakeep_keys
    networks:
      - karakeep
      - karakeep-web
    restart: unless-stopped
    labels:
      readme.description: The Bookmark Everything App
      readme.links.web: https://karakeep.app/
      traefik.docker.network: karakeep-web
      traefik.enable: true
      traefik.http.routers.karakeep.entrypoints: https
      traefik.http.routers.karakeep.rule: Host(`karakeep.${HOST}`)
      glance.id: karakeep
      glance.name: Karakeep
      glance.icon: di:karakeep
      glance.url: https://karakeep.${HOST}
      glance.description: Bookmark Manager
      glance.category: cloud
networks:
  karakeep:
    name: karakeep
  karakeep-web:
    name: karakeep-web
