name: ğŸ“ Generate README

on:
  push:
    paths:
      - '**docker-compose.yml'
      - '**docker-compose.*.yml'
      - 'README.tmpl.md'
    branches: [ "main" ]

concurrency:
  group: push

jobs:
  generate:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'chore(deps)')"

    steps:
      - name: ğŸ“¥ Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: ğŸ Install Python
        uses: actions/setup-python@8d9ed9ac5c53483de85588cdf95a591a75ab9f55 # v5 
        with:
          python-version: 'pypy3.9' 

      - name: ğŸ“¦ Install PyYAML
        run: |
          pip install pyyaml
          
      - name: ğŸ“ Generate README
        run: |
          python readme.py

      - name: ğŸš€ Commit & Push README
        run: |
          git pull
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git add README.md
          git commit -m "docs: update README.md" || true
          git push
