name: ğŸ“ Generate README

on:
  push:
    paths:
      - '**docker-compose.yml'
      - '**docker-compose.*.yml'
      - 'README.tmpl.md'
      - '.github/workflows/generate-readme.yml'
      - '.env.example'
    branches: [ "main" ]

concurrency:
  group: push

jobs:
  generate:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, 'chore(deps)') }}

    steps:
      - name: ğŸ“¥ Checkout Repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
          
      - name: ğŸ“ Generate README
        uses: ben-pearce/server-deployment-generate-readme@3241cc05d589d870d55e8a0741a09b1f210f6e77 # v1.2.3
        with:
          files: ./**/docker-compose*.yml
          template: .github/README.tmpl.md
