name: ğŸ“ Generate README

on:
  push:
    paths:
      - '**docker-compose.yml'
      - '**docker-compose.*.yml'
      - 'README.tmpl.md'
      - '.github/workflows/generate-readme.yml'
      - '.env.example'
    branches: [ "main" ]

concurrency:
  group: push

jobs:
  generate:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, 'chore(deps)') }}

    steps:
      - name: ğŸ“¥ Checkout Repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
          
      - name: ğŸ“ Generate README
        uses: ben-pearce/server-deployment-generate-readme@ad116fac24d1fcf350720f229abf6451644d7c23 # v1.1.1
        with:
          files: ./**/docker-compose*.yml
          template: .github/README.tmpl.md
