name: ğŸ“ Generate README

on:
  push:
    paths:
      - '**docker-compose.yml'
      - '**docker-compose.*.yml'
      - 'README.tmpl.md'
      - '.github/workflows/generate-readme.yml'
      - '.env.example'
    branches: [ "main" ]

concurrency:
  group: push

jobs:
  generate:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, 'chore(deps)') }}

    steps:
      - name: ğŸ“¥ Checkout Repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
          
      - name: ğŸ“ Generate README
        uses: ben-pearce/server-deployment-generate-readme@67f9220fd9984288b4c2395d2b5b423bcfb818ba # v1.2.5
        with:
          files: ./**/docker-compose*.yml
          template: .github/README.tmpl.md
