name: ğŸ“ Generate README

on:
  push:
    paths:
      - '**docker-compose.yml'
      - '**docker-compose.*.yml'
      - 'README.tmpl.md'
      - '.github/workflows/generate-readme.yml'
      - '.env.example'
    branches: [ "main" ]

concurrency:
  group: push

jobs:
  generate:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, 'chore(deps)') }}

    steps:
      - name: ğŸ“¥ Checkout Repository
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
          
      - name: ğŸ“ Generate README
        uses: ben-pearce/server-deployment-generate-readme@7dab54a4e8f9c283c9c273ebcdc4e89b7611fa5d # v1.1.0
        with:
          files: ./**/docker-compose*.yml
          template: .github/README.tmpl.md
